name: cairo_metro_gtfs
version: '1.0'
config-version: 2
profile: hotels_egypt_profile

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

models:
  cairo_metro_gtfs:
    +materialized: view
    staging:
      +schema: RAW_staging
    dimensions:
      +schema: RAW
    marts:
      +schema: RAW_marts
