version: 2

sources:
  - name: worldbank_raw
    database: ANALYTICS_DB
    schema: RAW
    tables:
      - name: worldbank_indicators
        identifier: WORLDBANK_INDICATORS
        description: "Raw World Bank development indicators data"

models:
  - name: stg_worldbank
    description: "Staging model for World Bank indicators data"
    columns:
      - name: record_id
        description: "Unique record identifier"
        tests:
          - not_null
          - unique
      - name: indicator_id
        description: "World Bank indicator code"
        tests:
          - not_null
      - name: country_id
        description: "ISO country code"
        tests:
          - not_null
      - name: year
        description: "Year of measurement"
        tests:
          - not_null
      - name: value
        description: "Indicator value"
        tests:
          - not_null

  - name: dim_country
    description: "Dimension table of countries"
    columns:
      - name: country_pk
        description: "Surrogate key for countries"
        tests:
          - not_null
          - unique
      - name: country_id
        description: "ISO country code"
        tests:
          - not_null
          - unique

  - name: dim_indicator
    description: "Dimension table of World Bank indicators"
    columns:
      - name: indicator_pk
        description: "Surrogate key for indicators"
        tests:
          - not_null
          - unique
      - name: indicator_id
        description: "World Bank indicator code"
        tests:
          - not_null
          - unique

  - name: fact_worldbank
    description: "Fact table of World Bank measurements"
    columns:
      - name: record_id
        description: "Unique record identifier"
        tests:
          - not_null
          - unique
      - name: country_id
        description: "Foreign key to dim_country"
        tests:
          - not_null
          - relationships:
              to: ref('dim_country')
              field: country_id
      - name: indicator_id
        description: "Foreign key to dim_indicator"
        tests:
          - not_null
          - relationships:
              to: ref('dim_indicator')
              field: indicator_id
      - name: value
        description: "Measurement value"
        tests:
          - not_null
